### ISSUE TITLE
List of residence halls overflows

### ISSUE THREAD

**Issue by shishirjessu** [thedailytexan/ut-dorm-explorer#2]
The list of residence halls will overflow lower than the map if you add a large number of dorms to the list. This can be fixed by changing the div class="homepage--compare-ng scope" to include a style attribute that allows scrolling when the div overflows.

**Comment by sc1f** [comment]
By overflow, do you mean covered by the footer? That's intentional. You're meant to scroll through the list.

**Comment by shishirjessu** [comment]
Exactly, you're meant to scroll through it - but instead of the list becoming scrollable, it simply overflows off the map

**Comment by sc1f** [comment]
Wait really? Shit. Post a screenshot here + what browser/OS you’re on. Thx!

**Comment by sc1f** [comment]
Fixed in latest commit.
